# Generated by Django 2.1 on 2018-08-23 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('carrier', models.SmallIntegerField(choices=[(1, 'TIM'), (1, 'Claro'), (1, 'Oi'), (1, 'Vivo')], verbose_name='Operadora')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ManyToManyField(to='core.Phone', verbose_name='Telefone'),
        ),
    ]
